# -*- coding: utf-8 -*-
"""MIT_Election_Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w9MZSxz9zWl_TL4VhUAGFppf18tectmB
"""

import pandas as pd

df = pd.read_csv("1976-2022-house.csv")

print(df.shape)
print(df.columns.tolist())
print(df.head())

print(df['year'].value_counts().sort_index())

# Check what values these columns have across all years
print("Stage values:")
print(df['stage'].value_counts())

print("\nRunoff values:")
print(df['runoff'].value_counts())

print("\nSpecial values:")
print(df['special'].value_counts())

print("\nParty values (top 20):")
print(df['party'].value_counts().head(20))

# Check specifically what 2012 looks like unfiltered
df_2012 = df[df['year'] == 2012]
print("\n2012 sample:")
print(df_2012[['year', 'stage', 'runoff', 'special', 'party', 'candidate']].head(10))

# Filter to 2012-2024, handling NaN values in runoff and special columns
df_filtered = df[
    (df['year'] >= 2012) &
    (df['stage'] == 'GEN') &
    (df['runoff'].fillna(False) == False) &
    (df['special'] == False) &
    (df['writein'] == False)
]

# Keep only major parties
df_filtered = df_filtered[df_filtered['party'].isin(['DEMOCRAT', 'REPUBLICAN'])].copy()

# Calculate vote share
df_filtered['vote_share'] = df_filtered['candidatevotes'] / df_filtered['totalvotes']

# Pivot to race level
race_level = df_filtered.groupby(['year', 'state', 'state_po', 'district', 'party'])['vote_share'].sum().unstack('party').reset_index()
race_level.columns = ['year', 'state', 'state_po', 'district', 'dem_share', 'rep_share']

# Calculate margin
race_level['margin'] = race_level['rep_share'] - race_level['dem_share']
race_level['winner'] = race_level['margin'].apply(lambda x: 'R' if x > 0 else 'D')
race_level['margin_abs'] = race_level['margin'].abs()

# Flag competitive districts
race_level['competitive'] = race_level['margin_abs'] < 0.10

# Fix at-large districts
race_level['district'] = race_level['district'].replace(0, 1)

# Create district ID
race_level['district_id'] = race_level['state_po'] + '-' + race_level['district'].astype(str).str.zfill(2)

# Drop uncontested races
race_level = race_level.dropna(subset=['dem_share', 'rep_share'])

# Inspect
print(race_level.shape)
print(f"\nCompetitive districts per year:")
print(race_level.groupby('year')['competitive'].sum())
print(f"\nSample rows:")
print(race_level.head())

# Save
race_level.to_csv("election_returns_clean.csv", index=False)
print("\nSaved to election_returns_clean.csv")
