# -*- coding: utf-8 -*-
"""04_create_relational_tables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zrqeqM2N7iXM6lA-shBRrZzsiWQ5iCCM
"""

import pandas as pd
import logging

# Set up logging
logging.basicConfig(
    filename='04_create_relational_tables.log',
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)

logging.info("Starting relational table creation")

try:
    # Load combined dataset
    combined = pd.read_csv("combined_dataset.csv")
    logging.info(f"Loaded combined dataset: {combined.shape}")

    # Table 1: districts
    districts = combined[['district_id', 'state', 'state_po', 'district']].drop_duplicates().reset_index(drop=True)
    logging.info(f"Districts table: {districts.shape}")

    # Table 2: years
    unique_years = sorted(combined['year'].unique())
    years_data = []
    for y in unique_years:
        congress_num = int((y - 1789) / 2 + 1)
        redistricting = True if y in [2012, 2022] else False
        years_data.append({'year': y, 'congress_number': congress_num, 'redistricting_cycle': redistricting})
    years = pd.DataFrame(years_data)
    logging.info(f"Years table: {years.shape}")

    # Table 3: election_results
    election_results = combined[['district_id', 'year', 'dem_share', 'rep_share', 'margin', 'winner', 'margin_abs', 'competitive']].copy()
    election_results.insert(0, 'result_id', range(1, len(election_results) + 1))
    logging.info(f"Election results table: {election_results.shape}")

    # Table 4: demographics
    demographics = combined[['district_id', 'year', 'total_population', 'median_income', 'pct_college', 'pct_hs_only', 'pct_white', 'pct_black', 'pct_asian', 'pct_hispanic', 'pct_nonwhite']].copy()
    demographics.insert(0, 'demo_id', range(1, len(demographics) + 1))
    logging.info(f"Demographics table: {demographics.shape}")

    # Save
    districts.to_csv("districts.csv", index=False)
    years.to_csv("years.csv", index=False)
    election_results.to_csv("election_results.csv", index=False)
    demographics.to_csv("demographics.csv", index=False)

    logging.info("All four tables saved successfully")
    print(f"districts.csv:        {districts.shape}")
    print(f"years.csv:            {years.shape}")
    print(f"election_results.csv: {election_results.shape}")
    print(f"demographics.csv:     {demographics.shape}")

except Exception as e:
    logging.error(f"Error: {e}")
    print(f"Error: {e}")
    raise

