# -*- coding: utf-8 -*-
"""05_margins_&_party_lines.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11IexmUREKLhwVhF1njJlvHtUSpL-iV6S
"""

"""
05_enrich_further.py
--------------------
Stage 5 of the House Elections pipeline. Takes the already-enriched
combined dataset (output of 04_enrich_dataset.py) and adds:

  1.  Lagged margin        — prior cycle's margin for each district
  2.  Lagged winner        — party that won the prior cycle
  3.  Party flip           — did the seat change party from prior cycle
  4.  Dem swing            — change in dem_share vs. prior cycle
  5.  Competitiveness score — 1 - abs(margin), higher = more competitive
  6.  District vs. generic  — district margin minus national generic ballot
  7.  Presidential context  — national pres popular-vote margin for nearest
                              prior presidential election year
  8.  National economic indicators — unemployment, GDP growth, pres approval
  9.  Urban/rural classification  — NCHS 6-level scheme (state-level proxy)
  10. Additional ACS variables    — poverty rate, unemployment rate,
                                    median age, median home value,
                                    owner occupancy rate, health ins rate
                                    (pulled from Census API)

Dependencies:
  pip install pandas requests pyarrow
"""

import logging
import os
import sys
import time

import requests
import pandas as pd

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler("/content/05_enrich_further.log"),
        logging.StreamHandler(sys.stdout),
    ],
)
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
INPUT_PATH     = "/content/combined_dataset_enriched.csv"  # upload this to Colab sidebar first
OUTPUT_CSV     = "/content/combined_dataset_master.csv"    # download from Colab sidebar when done
OUTPUT_PARQUET = "/content/combined_dataset_master.parquet"  # download from Colab sidebar when done

# Optional Census API key — keyless works but may be rate-limited
# Get one free at: https://api.census.gov/data/key_signup.html
CENSUS_API_KEY = ""


# ===========================================================================
# 1. LOAD
# ===========================================================================
def load_base(path: str) -> pd.DataFrame:
    """Load combined_dataset_enriched.csv (output of step 04)."""
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"File not found: {path}\n"
            "Upload combined_dataset_enriched.csv first."
        )
    df = pd.read_csv(path)
    log.info(f"Loaded {path}: {len(df):,} rows x {df.shape[1]} columns")
    log.info(f"Columns present: {list(df.columns)}")
    return df


# ===========================================================================
# 2. LAGGED FEATURES + PARTY FLIP
# ===========================================================================
def add_lagged_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    For each district-year, look up margin and winner from the prior
    election cycle (year - 2). Also flags whether the seat flipped party.

    Requires columns: district_id, year, margin, winner
    """
    log.info("Computing lagged margin, lagged winner, party flip, dem swing...")

    df = df.sort_values(["district_id", "year"]).reset_index(drop=True)

    # Build prior-cycle lookup
    lag_src = (
        df[["district_id", "year", "margin", "winner", "dem_share"]]
        .copy()
        .rename(columns={
            "margin":    "prev_margin",
            "winner":    "prev_winner",
            "dem_share": "dem_share_lag",
            "year":      "prev_year",
        })
    )
    # Shift forward 2 years so we can join on current year
    lag_src["year"] = lag_src["prev_year"] + 2

    df = df.merge(
        lag_src[["district_id", "year", "prev_margin", "prev_winner", "dem_share_lag"]],
        on=["district_id", "year"],
        how="left",
    )

    # Party flip: seat changed hands vs. prior cycle
    df["party_flip"] = (
        df["prev_winner"].notna() & (df["winner"] != df["prev_winner"])
    )

    # Dem vote share swing vs. prior cycle
    df["dem_swing"] = df["dem_share"] - df["dem_share_lag"]

    log.info(
        f"  prev_margin filled for {df['prev_margin'].notna().sum():,}"
        f" / {len(df):,} rows"
    )
    return df


# ===========================================================================
# 3. DERIVED FEATURES
# ===========================================================================
def add_derived_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Competitiveness score and district-vs-national-environment features.
    Requires: margin_abs, generic_ballot_margin, margin
    """
    log.info("Adding derived features...")

    # Competitiveness: 1 = perfectly competitive, 0 = completely safe
    df["competitiveness_score"] = (1 - df["margin_abs"]).clip(0, 1)

    # How much does this district deviate from the national environment?
    if "generic_ballot_margin" in df.columns:
        df["district_vs_generic"] = df["margin"] - df["generic_ballot_margin"]
        log.info("  district_vs_generic added")
    else:
        log.warning("  generic_ballot_margin not found — skipping district_vs_generic")

    log.info("  competitiveness_score added")
    return df


# ===========================================================================
# 4. PRESIDENTIAL CONTEXT
# ===========================================================================
# National two-party presidential popular-vote margin (Dem - Rep, in pct pts)
# Positive = Democrat won popular vote by that margin.
# Sources: Federal Election Commission certified results.
NATIONAL_PRES_MARGIN = {
    2012:  3.9,   # Obama +3.9
    2016:  2.1,   # Clinton +2.1 popular vote (lost EC)
    2020:  4.5,   # Biden +4.5
}

def add_presidential_context(df: pd.DataFrame) -> pd.DataFrame:
    """
    For each election year, finds the most recent prior presidential year
    and attaches that election's national popular-vote margin.
    """
    log.info("Adding presidential popular-vote context...")

    def nearest_pres(year):
        for y in [year, year - 1, year - 2, year - 3]:
            if y in NATIONAL_PRES_MARGIN:
                return NATIONAL_PRES_MARGIN[y], y
        return None, None

    df[["pres_popular_margin", "pres_year"]] = df["year"].apply(
        lambda y: pd.Series(nearest_pres(y))
    )

    log.info("  pres_popular_margin, pres_year added")
    return df


# ===========================================================================
# 5. NATIONAL ECONOMIC INDICATORS
# ===========================================================================
# Year-level national fundamentals used in structural forecasting models.
# Sources:
#   Unemployment: BLS annual average (https://data.bls.gov)
#   GDP growth:   BEA annual real GDP growth (https://apps.bea.gov)
#   Pres approval: Gallup annual average (https://news.gallup.com)
ECONOMIC_INDICATORS = {
    # year: (unemployment_rate_pct, gdp_growth_pct, pres_approval_pct)
    2012: (8.1,  2.3, 49.1),
    2014: (6.2,  2.5, 42.6),
    2016: (4.7,  1.7, 48.5),
    2018: (3.9,  3.0, 42.0),
    2020: (8.1, -3.4, 41.9),
    2022: (3.6,  2.1, 40.4),
}

def add_economic_indicators(df: pd.DataFrame) -> pd.DataFrame:
    """Merge national economic fundamentals by election year."""
    log.info("Adding national economic indicators...")

    econ = pd.DataFrame.from_dict(
        ECONOMIC_INDICATORS,
        orient="index",
        columns=["natl_unemployment_rate", "natl_gdp_growth", "pres_approval"],
    )
    econ.index.name = "year"
    econ = econ.reset_index()

    df = df.merge(econ, on="year", how="left")
    log.info("  natl_unemployment_rate, natl_gdp_growth, pres_approval added")
    return df


# ===========================================================================
# 6. URBAN / RURAL CLASSIFICATION
# ===========================================================================
# NCHS Urban-Rural Classification Scheme for Counties, 2013 edition.
# https://www.cdc.gov/nchs/data_access/urban_rural.htm
# Levels: 1=Large central metro, 2=Large fringe metro, 3=Medium metro,
#         4=Small metro, 5=Micropolitan, 6=Noncore (rural)
# Applied here at state level as a tractable proxy.
# For district-level precision, join a county-to-CD crosswalk separately.
STATE_URBAN_CLASS = {
    "AL": 4, "AK": 5, "AZ": 2, "AR": 5, "CA": 1, "CO": 2, "CT": 2,
    "DE": 3, "FL": 1, "GA": 1, "HI": 3, "ID": 5, "IL": 1, "IN": 3,
    "IA": 4, "KS": 4, "KY": 4, "LA": 3, "ME": 5, "MD": 1, "MA": 1,
    "MI": 2, "MN": 2, "MS": 5, "MO": 3, "MT": 6, "NE": 4, "NV": 2,
    "NH": 3, "NJ": 1, "NM": 4, "NY": 1, "NC": 3, "ND": 6, "OH": 2,
    "OK": 4, "OR": 3, "PA": 2, "RI": 2, "SC": 3, "SD": 6, "TN": 3,
    "TX": 1, "UT": 2, "VT": 5, "VA": 2, "WA": 2, "WV": 5, "WI": 3,
    "WY": 6,
}
URBAN_CLASS_LABELS = {
    1: "Large central metro",
    2: "Large fringe metro",
    3: "Medium metro",
    4: "Small metro",
    5: "Micropolitan",
    6: "Noncore/Rural",
}

def add_urban_rural(df: pd.DataFrame) -> pd.DataFrame:
    """Add NCHS 6-level urban/rural classification (state-level proxy)."""
    log.info("Adding urban/rural classification...")
    df["urban_rural_code"]  = df["state_po"].map(STATE_URBAN_CLASS)
    df["urban_rural_label"] = df["urban_rural_code"].map(URBAN_CLASS_LABELS)
    log.info("  urban_rural_code, urban_rural_label added")
    return df


# ===========================================================================
# 7. ADDITIONAL ACS VARIABLES (Census API)
# ===========================================================================
# These complement the ACS variables already pulled in step 02 (Demographics).
# Step 02 pulled: education, race, income, population.
# This step adds: poverty, unemployment, age, home value, housing tenure,
#                 health insurance coverage.

ACS_EXTRA_VARS = {
    "B17001_002E": "poverty_count",       # People below poverty level
    "B17001_001E": "poverty_universe",    # Total for poverty calc
    "B23025_005E": "unemployed_count",    # Civilian unemployed
    "B23025_002E": "labor_force_total",   # Civilian labor force
    "B01002_001E": "median_age",          # Median age
    "B25077_001E": "median_home_value",   # Median home value
    "B25003_002E": "owner_occupied",      # Owner-occupied units
    "B25003_001E": "total_housing_units", # Total occupied units
    "B27001_001E": "health_ins_universe", # Health insurance universe
    "B27001_002E": "with_health_ins",     # With health insurance
}

# Election year -> ACS 5-year estimate year (matches step 02 logic)
ACS_YEAR_MAP = {
    2012: 2012,
    2014: 2014,
    2016: 2016,
    2018: 2018,
    2020: 2020,
    2022: 2022,
}

# Postal abbreviation -> FIPS (matches step 02)
POSTAL_TO_FIPS = {
    "AL":"01","AK":"02","AZ":"04","AR":"05","CA":"06","CO":"08","CT":"09",
    "DE":"10","FL":"12","GA":"13","HI":"15","ID":"16","IL":"17","IN":"18",
    "IA":"19","KS":"20","KY":"21","LA":"22","ME":"23","MD":"24","MA":"25",
    "MI":"26","MN":"27","MS":"28","MO":"29","MT":"30","NE":"31","NV":"32",
    "NH":"33","NJ":"34","NM":"35","NY":"36","NC":"37","ND":"38","OH":"39",
    "OK":"40","OR":"41","PA":"42","RI":"44","SC":"45","SD":"46","TN":"47",
    "TX":"48","UT":"49","VT":"50","VA":"51","WA":"53","WV":"54","WI":"55",
    "WY":"56",
}

def _pull_acs_extra_one_state(state_po: str, acs_year: int,
                               api_key: str) -> list[dict]:
    """Pull extra ACS variables for all districts in one state-year."""
    fips = POSTAL_TO_FIPS.get(state_po)
    if not fips:
        return []

    vars_str = ",".join(ACS_EXTRA_VARS.keys())
    url = (
        f"https://api.census.gov/data/{acs_year}/acs/acs5"
        f"?get=NAME,{vars_str}"
        f"&for=congressional+district:*"
        f"&in=state:{fips}"
        + (f"&key={api_key}" if api_key else "")
    )
    try:
        resp = requests.get(url, timeout=20)
        resp.raise_for_status()
        data = resp.json()
        records = []
        header = data[0]
        for row in data[1:]:
            raw = dict(zip(header, row))
            cd_num = raw.get("congressional district", "00")
            district_id = f"{state_po}-{cd_num.zfill(2)}"
            rec = {"district_id": district_id, "acs_year": acs_year}
            for api_var, col_name in ACS_EXTRA_VARS.items():
                val = raw.get(api_var)
                try:
                    rec[col_name] = float(val) if val is not None else None
                except (ValueError, TypeError):
                    rec[col_name] = None
            records.append(rec)
        return records
    except Exception as e:
        log.warning(f"  ACS extra pull failed — {state_po} {acs_year}: {e}")
        return []


def add_acs_extra_variables(df: pd.DataFrame, api_key: str) -> pd.DataFrame:
    """
    Pull additional ACS variables for every unique state-year combo,
    compute derived rates, and merge back into the main dataframe.
    Reuses the same Census API endpoint as step 02 (Demographics).
    """
    log.info("Pulling additional ACS variables from Census API...")

    df["acs_year"] = df["year"].map(ACS_YEAR_MAP)
    unique_combos = (
        df[["state_po", "acs_year"]].drop_duplicates().dropna()
    )
    log.info(f"  {len(unique_combos)} unique state-year combos to pull")

    all_records = []
    for i, (_, row) in enumerate(unique_combos.iterrows()):
        records = _pull_acs_extra_one_state(
            row["state_po"], int(row["acs_year"]), api_key
        )
        all_records.extend(records)
        if (i + 1) % 10 == 0:
            log.info(f"  {i+1}/{len(unique_combos)} states pulled...")
        time.sleep(0.3)   # be polite to the Census API

    if not all_records:
        log.warning("No ACS extra records pulled — skipping")
        df = df.drop(columns=["acs_year"])
        return df

    acs_extra = pd.DataFrame(all_records)

    # Replace Census sentinel missing values
    import numpy as np
    num_cols = list(ACS_EXTRA_VARS.values())
    acs_extra[num_cols] = acs_extra[num_cols].apply(
        pd.to_numeric, errors="coerce"
    )
    acs_extra[num_cols] = acs_extra[num_cols].where(
        acs_extra[num_cols] >= 0, np.nan
    )

    # Compute rates
    acs_extra["poverty_rate"] = (
        acs_extra["poverty_count"] / acs_extra["poverty_universe"]
    ).clip(0, 1)
    acs_extra["district_unemployment_rate"] = (
        acs_extra["unemployed_count"] / acs_extra["labor_force_total"]
    ).clip(0, 1)
    acs_extra["owner_occ_rate"] = (
        acs_extra["owner_occupied"] / acs_extra["total_housing_units"]
    ).clip(0, 1)
    acs_extra["health_ins_rate"] = (
        acs_extra["with_health_ins"] / acs_extra["health_ins_universe"]
    ).clip(0, 1)

    # Keep only derived rates + useful continuous vars; drop raw counts
    keep = [
        "district_id", "acs_year",
        "poverty_rate", "district_unemployment_rate",
        "median_age", "median_home_value",
        "owner_occ_rate", "health_ins_rate",
    ]
    acs_extra = acs_extra[[c for c in keep if c in acs_extra.columns]]

    df = df.merge(acs_extra, on=["district_id", "acs_year"], how="left")
    df = df.drop(columns=["acs_year"])

    filled = df["poverty_rate"].notna().sum()
    log.info(f"  ACS extra variables merged: {filled:,} / {len(df):,} rows filled")
    return df


# ===========================================================================
# 8. SAVE
# ===========================================================================
def save_outputs(df: pd.DataFrame) -> None:
    """Save master dataset as both CSV and Parquet."""

    # --- CSV ---
    log.info(f"Saving CSV -> {OUTPUT_CSV}")
    df.to_csv(OUTPUT_CSV, index=False)
    csv_mb = os.path.getsize(OUTPUT_CSV) / 1e6
    log.info(f"  CSV size: {csv_mb:.2f} MB")
    print(f"\n  CSV saved: {OUTPUT_CSV}  ({csv_mb:.2f} MB)")

    # --- Parquet ---
    # Parquet is strongly preferred for DuckDB: 5-10x smaller, faster to load,
    # and preserves dtypes (no re-parsing strings as dates/booleans on read).
    log.info(f"Saving Parquet -> {OUTPUT_PARQUET}")
    try:
        df.to_parquet(OUTPUT_PARQUET, index=False, compression="snappy")
        pq_mb = os.path.getsize(OUTPUT_PARQUET) / 1e6
        log.info(f"  Parquet size: {pq_mb:.2f} MB")
        print(f"  Parquet saved: {OUTPUT_PARQUET}  ({pq_mb:.2f} MB)")
    except ImportError:
        log.warning("pyarrow not installed — skipping parquet. Run: pip install pyarrow")
    except Exception as e:
        log.error(f"Parquet save failed: {e}")

    print(f"\n  Final shape: {df.shape[0]:,} rows x {df.shape[1]} columns")
    print(f"  Columns: {list(df.columns)}")


# ===========================================================================
# MAIN
# ===========================================================================
def main():
    print("=" * 60)
    print("Step 05 — Further enrichment of combined_dataset_enriched.csv")
    print("=" * 60)

    print("\n[1/7] Loading base dataset...")
    df = load_base(INPUT_PATH)

    print("\n[2/7] Adding lagged margin, party flip, dem swing...")
    df = add_lagged_features(df)

    print("\n[3/7] Adding competitiveness score and district vs. generic...")
    df = add_derived_features(df)

    print("\n[4/7] Adding presidential popular-vote context...")
    df = add_presidential_context(df)

    print("\n[5/7] Adding national economic indicators...")
    df = add_economic_indicators(df)

    print("\n[6/7] Adding urban/rural classification...")
    df = add_urban_rural(df)

    print("\n[7/7] Pulling additional ACS variables from Census API...")
    print("  (makes ~1 call per state per year — ~250 calls total, ~2-3 min)")
    df = add_acs_extra_variables(df, CENSUS_API_KEY)

    # Final sort
    df = df.sort_values(["district_id", "year"]).reset_index(drop=True)

    print("\nSaving outputs...")
    save_outputs(df)

    print("\nDone. Log at /content/05_enrich_further.log")
    print("=" * 60)


if __name__ == "__main__":
    main()