# -*- coding: utf-8 -*-
"""Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hGYznPcBjjUmTuqzZae3Bc32_c0AqfrH
"""

"""
06_pipeline.py

Pipeline stages:
  1. Load master parquet into DuckDB
  2. Create relational schema (5 tables)
  3. SQL queries for data preparation
  4. ML model: predicting party flip / competitive outcome
  5. Visualization of results


Table schema (relational model):
  districts       — one row per district (static geography/identity)
  elections       — one row per district-year (vote outcomes)
  demographics    — one row per district-year (ACS socioeconomic)
  national_context— one row per election year (macro environment)
  results_model   — one row per district-year (model predictions, written back)
"""

import logging
import sys
import duckdb
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import seaborn as sns
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    classification_report, confusion_matrix, roc_auc_score, roc_curve
)
from sklearn.pipeline import Pipeline

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler("/content/06_pipeline.log"),
        logging.StreamHandler(sys.stdout),
    ],
)
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
PARQUET_PATH = "/content/combined_dataset_master.parquet"
DB_PATH      = "/content/house_elections.duckdb"   # persistent DuckDB file

# ===========================================================================
# STAGE 1 — Connect to DuckDB and load parquet
# ===========================================================================
log.info("=" * 60)
log.info("STAGE 1: Connecting to DuckDB")
log.info("=" * 60)

try:
    con = duckdb.connect(DB_PATH)
    log.info(f"Connected to DuckDB at {DB_PATH}")
except Exception as e:
    log.error(f"DuckDB connection failed: {e}")
    sys.exit(1)

# Register the parquet file as a virtual table so we can query it directly
# before we decompose it into relational tables
con.execute(f"""
    CREATE OR REPLACE VIEW master_raw AS
    SELECT * FROM read_parquet('{PARQUET_PATH}')
""")

row_count = con.execute("SELECT COUNT(*) FROM master_raw").fetchone()[0]
log.info(f"Parquet loaded: {row_count:,} rows visible via master_raw view")

# ===========================================================================
# STAGE 2 — Create relational schema (5 tables)
# ===========================================================================
log.info("=" * 60)
log.info("STAGE 2: Creating relational tables")
log.info("=" * 60)

# ---------------------------------------------------------------------------
# TABLE 1: districts
# One row per congressional district (static identity / geography).
# Primary key: district_id
# ---------------------------------------------------------------------------
con.execute("""
    CREATE OR REPLACE TABLE districts AS
    SELECT DISTINCT
        district_id,
        state,
        state_po,
        district,
        urban_rural_code,
        urban_rural_label
    FROM master_raw
    ORDER BY district_id
""")
n = con.execute("SELECT COUNT(*) FROM districts").fetchone()[0]
log.info(f"  districts: {n:,} rows (1 per congressional district)")

# ---------------------------------------------------------------------------
# TABLE 2: elections
# One row per district-year (vote outcomes and incumbency).
# Primary key: (district_id, year)
# Foreign key: district_id -> districts
# ---------------------------------------------------------------------------
con.execute("""
    CREATE OR REPLACE TABLE elections AS
    SELECT
        district_id,
        year,
        dem_share,
        rep_share,
        margin,
        margin_abs,
        winner,
        competitive,
        competitiveness_score,
        incumbent_running,
        open_seat,
        prev_margin,
        prev_winner,
        dem_share_lag,
        party_flip,
        dem_swing,
        redistricting_year
    FROM master_raw
    ORDER BY district_id, year
""")
n = con.execute("SELECT COUNT(*) FROM elections").fetchone()[0]
log.info(f"  elections: {n:,} rows (1 per district-year)")

# ---------------------------------------------------------------------------
# TABLE 3: demographics
# One row per district-year (ACS socioeconomic features).
# Primary key: (district_id, year)
# Foreign key: district_id -> districts
# ---------------------------------------------------------------------------
con.execute("""
    CREATE OR REPLACE TABLE demographics AS
    SELECT
        district_id,
        year,
        total_population,
        cvap_total,
        median_income,
        median_age,
        median_home_value,
        pct_college,
        pct_hs_only,
        pct_white,
        pct_black,
        pct_asian,
        pct_hispanic,
        pct_nonwhite,
        poverty_rate,
        district_unemployment_rate,
        owner_occ_rate,
        health_ins_rate
    FROM master_raw
    ORDER BY district_id, year
""")
n = con.execute("SELECT COUNT(*) FROM demographics").fetchone()[0]
log.info(f"  demographics: {n:,} rows (1 per district-year)")

# ---------------------------------------------------------------------------
# TABLE 4: national_context
# One row per election year (macro-level environment).
# Primary key: year
# ---------------------------------------------------------------------------
con.execute("""
    CREATE OR REPLACE TABLE national_context AS
    SELECT DISTINCT
        year,
        generic_ballot_margin,
        pres_popular_margin,
        pres_year,
        natl_unemployment_rate,
        natl_gdp_growth,
        pres_approval
    FROM master_raw
    ORDER BY year
""")
n = con.execute("SELECT COUNT(*) FROM national_context").fetchone()[0]
log.info(f"  national_context: {n:,} rows (1 per election year)")

# ---------------------------------------------------------------------------
# TABLE 5: results_model
# Placeholder — will be populated in Stage 4 with model predictions.
# Primary key: (district_id, year)
# Foreign key: district_id -> districts
# ---------------------------------------------------------------------------
con.execute("""
    CREATE OR REPLACE TABLE results_model (
        district_id             VARCHAR,
        year                    INTEGER,
        predicted_flip          BOOLEAN,
        predicted_competitive   BOOLEAN,
        flip_probability        DOUBLE,
        model_name              VARCHAR,
        PRIMARY KEY (district_id, year)
    )
""")
log.info("  results_model: empty placeholder (populated in Stage 4)")

# Verify all tables exist
tables = con.execute("SHOW TABLES").fetchdf()
log.info(f"\nAll tables in DB: {tables['name'].tolist()}")

# ===========================================================================
# STAGE 3 — SQL queries for data preparation
# ===========================================================================
log.info("=" * 60)
log.info("STAGE 3: SQL queries for data preparation")
log.info("=" * 60)

# ---------------------------------------------------------------------------
# Query 1: Join all tables into analysis-ready flat view
# This is the primary analytical dataset used by the model.
# ---------------------------------------------------------------------------
con.execute("""
    CREATE OR REPLACE VIEW analysis_view AS
    SELECT
        e.district_id,
        e.year,

        -- Election outcomes
        e.dem_share,
        e.rep_share,
        e.margin,
        e.margin_abs,
        e.winner,
        e.competitive,
        e.competitiveness_score,
        e.incumbent_running,
        e.open_seat,
        e.prev_margin,
        e.prev_winner,
        e.dem_share_lag,
        e.party_flip,
        e.dem_swing,
        e.redistricting_year,

        -- Geography
        d.state_po,
        d.urban_rural_code,
        d.urban_rural_label,

        -- Demographics
        dm.total_population,
        dm.cvap_total,
        dm.median_income,
        dm.median_age,
        dm.median_home_value,
        dm.pct_college,
        dm.pct_hs_only,
        dm.pct_white,
        dm.pct_black,
        dm.pct_asian,
        dm.pct_hispanic,
        dm.pct_nonwhite,
        dm.poverty_rate,
        dm.district_unemployment_rate,
        dm.owner_occ_rate,
        dm.health_ins_rate,

        -- National environment
        nc.generic_ballot_margin,
        nc.pres_popular_margin,
        nc.natl_unemployment_rate,
        nc.natl_gdp_growth,
        nc.pres_approval

    FROM elections e
    JOIN districts d        ON e.district_id = d.district_id
    JOIN demographics dm    ON e.district_id = dm.district_id AND e.year = dm.year
    JOIN national_context nc ON e.year = nc.year
""")
n = con.execute("SELECT COUNT(*) FROM analysis_view").fetchone()[0]
log.info(f"  analysis_view: {n:,} rows (full join across all 4 tables)")

# ---------------------------------------------------------------------------
# Query 2: Competitive districts by year and party
# ---------------------------------------------------------------------------
q2 = con.execute("""
    SELECT
        year,
        winner,
        COUNT(*)                            AS total_districts,
        SUM(CASE WHEN competitive THEN 1 ELSE 0 END) AS competitive_count,
        ROUND(AVG(margin_abs) * 100, 2)    AS avg_margin_pct,
        ROUND(AVG(dem_share)  * 100, 2)    AS avg_dem_share_pct
    FROM elections
    GROUP BY year, winner
    ORDER BY year, winner
""").fetchdf()
log.info(f"\nQuery 2 — Competitive districts by year/party:\n{q2.to_string()}")

# ---------------------------------------------------------------------------
# Query 3: Seats that flipped, with prior and current margin
# ---------------------------------------------------------------------------
q3 = con.execute("""
    SELECT
        district_id,
        year,
        prev_winner,
        winner,
        ROUND(prev_margin * 100, 1) AS prior_margin_pct,
        ROUND(margin * 100, 1)      AS current_margin_pct,
        ROUND(dem_swing * 100, 1)   AS dem_swing_pct
    FROM elections
    WHERE party_flip = TRUE
    ORDER BY year, district_id
""").fetchdf()
log.info(f"\nQuery 3 — Flipped seats ({len(q3)} total):\n{q3.head(10).to_string()}")

# ---------------------------------------------------------------------------
# Query 4: Demographic profile of competitive vs. safe districts
# ---------------------------------------------------------------------------
q4 = con.execute("""
    SELECT
        CASE WHEN e.competitive THEN 'Competitive (<10%)' ELSE 'Safe (>=10%)' END AS district_type,
        COUNT(*)                                    AS n,
        ROUND(AVG(dm.median_income), 0)             AS avg_median_income,
        ROUND(AVG(dm.pct_college)  * 100, 1)        AS avg_pct_college,
        ROUND(AVG(dm.pct_nonwhite) * 100, 1)        AS avg_pct_nonwhite,
        ROUND(AVG(dm.poverty_rate) * 100, 1)        AS avg_poverty_rate,
        ROUND(AVG(dm.median_age),  1)               AS avg_median_age,
        ROUND(AVG(d.urban_rural_code), 2)           AS avg_urban_rural_code
    FROM elections e
    JOIN demographics dm ON e.district_id = dm.district_id AND e.year = dm.year
    JOIN districts d     ON e.district_id = d.district_id
    GROUP BY district_type
    ORDER BY district_type
""").fetchdf()
log.info(f"\nQuery 4 — Demographics by district competitiveness:\n{q4.to_string()}")

# ---------------------------------------------------------------------------
# Query 5: National environment effect — generic ballot vs. seat swings
# ---------------------------------------------------------------------------
q5 = con.execute("""
    SELECT
        nc.year,
        nc.generic_ballot_margin,
        nc.natl_unemployment_rate,
        nc.pres_approval,
        COUNT(*)                                         AS total_seats,
        SUM(CASE WHEN e.party_flip THEN 1 ELSE 0 END)   AS flipped_seats,
        SUM(CASE WHEN e.winner = 'D' THEN 1 ELSE 0 END) AS dem_seats,
        SUM(CASE WHEN e.winner = 'R' THEN 1 ELSE 0 END) AS rep_seats,
        ROUND(AVG(e.dem_share) * 100, 2)                AS avg_dem_share_pct
    FROM elections e
    JOIN national_context nc ON e.year = nc.year
    GROUP BY nc.year, nc.generic_ballot_margin,
             nc.natl_unemployment_rate, nc.pres_approval
    ORDER BY nc.year
""").fetchdf()
log.info(f"\nQuery 5 — National environment by year:\n{q5.to_string()}")

# ---------------------------------------------------------------------------
# Query 6: Top 10 most consistently competitive districts (all cycles)
# ---------------------------------------------------------------------------
q6 = con.execute("""
    SELECT
        district_id,
        COUNT(*)                                AS cycles,
        SUM(CASE WHEN competitive THEN 1 ELSE 0 END) AS competitive_cycles,
        ROUND(AVG(margin_abs) * 100, 2)         AS avg_margin_pct,
        ROUND(MIN(margin_abs) * 100, 2)         AS min_margin_pct,
        STRING_AGG(winner, ',' ORDER BY year)   AS winner_sequence
    FROM elections
    GROUP BY district_id
    HAVING COUNT(*) >= 4
    ORDER BY avg_margin_pct ASC
    LIMIT 10
""").fetchdf()
log.info(f"\nQuery 6 — Most competitive districts:\n{q6.to_string()}")

# ===========================================================================
# STAGE 4 — ML Model: Predicting Party Flip
# ===========================================================================
log.info("=" * 60)
log.info("STAGE 4: ML Model — Predicting Party Flip")
log.info("=" * 60)

# Pull analysis view into pandas for sklearn
df = con.execute("SELECT * FROM analysis_view").fetchdf()
log.info(f"Analysis view loaded into pandas: {df.shape}")

# ---------------------------------------------------------------------------
# Feature selection rationale:
#   - prev_margin: strongest single predictor (safe seats rarely flip)
#   - dem_swing: momentum from prior cycle
#   - generic_ballot_margin: national environment (wave elections)
#   - pres_approval: presidential drag effect
#   - natl_gdp_growth / natl_unemployment_rate: economic fundamentals
#   - pct_college, pct_nonwhite, median_income: demographic lean
#   - urban_rural_code: structural partisan lean
#   - redistricting_year: structural disruption
# ---------------------------------------------------------------------------
FEATURES = [
    "prev_margin",
    "dem_swing",
    "generic_ballot_margin",
    "pres_approval",
    "natl_gdp_growth",
    "natl_unemployment_rate",
    "pct_college",
    "pct_nonwhite",
    "median_income",
    "urban_rural_code",
    "poverty_rate",
    "median_age",
    "health_ins_rate",
]
TARGET = "party_flip"

# Drop rows where target or key features are missing
model_df = df[FEATURES + [TARGET, "district_id", "year"]].dropna()
log.info(f"Rows available for modeling (after dropna): {len(model_df):,}")

X = model_df[FEATURES].values
y = model_df[TARGET].astype(int).values

# Train/test split — hold out 2022 as test year to avoid data leakage
test_mask  = model_df["year"] == 2022
X_train, X_test = X[~test_mask], X[test_mask]
y_train, y_test = y[~test_mask], y[test_mask]
log.info(f"Train: {len(X_train):,} rows | Test (2022): {len(X_test):,} rows")

# ---------------------------------------------------------------------------
# Model: Gradient Boosting Classifier
# Chosen over logistic regression because:
#   - Handles non-linear interactions (e.g. incumbency x national environment)
#   - Robust to feature scale differences without needing normalization
#   - Strong empirical performance on tabular election data in literature
# ---------------------------------------------------------------------------
gb_model = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    min_samples_leaf=10,
    random_state=42,
)
gb_model.fit(X_train, y_train)

# Cross-validation on training set
cv_scores = cross_val_score(gb_model, X_train, y_train,
                             cv=5, scoring="roc_auc")
log.info(f"5-fold CV ROC-AUC: {cv_scores.mean():.3f} ± {cv_scores.std():.3f}")

# Test set evaluation
y_pred      = gb_model.predict(X_test)
y_prob      = gb_model.predict_proba(X_test)[:, 1]
test_auc    = roc_auc_score(y_test, y_prob)
log.info(f"Test ROC-AUC (2022): {test_auc:.3f}")
log.info(f"\nClassification report (2022 holdout):\n"
         f"{classification_report(y_test, y_pred, target_names=['Safe','Flip'])}")

# Feature importances
feat_imp = pd.DataFrame({
    "feature":   FEATURES,
    "importance": gb_model.feature_importances_,
}).sort_values("importance", ascending=False)
log.info(f"\nFeature importances:\n{feat_imp.to_string()}")

# ---------------------------------------------------------------------------
# Write predictions back to DuckDB results_model table
# ---------------------------------------------------------------------------
results_df = model_df[["district_id", "year"]].copy()
results_df["predicted_flip"]        = gb_model.predict(X).astype(bool)
results_df["flip_probability"]      = gb_model.predict_proba(X)[:, 1]
results_df["predicted_competitive"] = results_df["flip_probability"] > 0.15
results_df["model_name"]            = "GradientBoostingClassifier"

con.execute("DELETE FROM results_model")
con.register("results_temp", results_df)
con.execute("""
    INSERT INTO results_model
    SELECT district_id, year, predicted_flip,
           predicted_competitive, flip_probability, model_name
    FROM results_temp
""")
n = con.execute("SELECT COUNT(*) FROM results_model").fetchone()[0]
log.info(f"results_model populated: {n:,} rows")

# ===========================================================================
# STAGE 5 — Visualizations
# ===========================================================================
log.info("=" * 60)
log.info("STAGE 5: Visualizations")
log.info("=" * 60)

# Publication-quality style
plt.rcParams.update({
    "font.family":      "DejaVu Sans",
    "font.size":        11,
    "axes.titlesize":   13,
    "axes.titleweight": "bold",
    "axes.spines.top":  False,
    "axes.spines.right":False,
    "figure.dpi":       150,
})
BLUE = "#2166AC"
RED  = "#D6604D"
GRAY = "#888888"

# ---------------------------------------------------------------------------
# Figure 1: Seat counts by party and year with generic ballot overlay
# Rationale: shows national wave patterns and connects macro environment
#            to district-level outcomes — core motivation for the project.
# ---------------------------------------------------------------------------
fig, ax1 = plt.subplots(figsize=(10, 5))

seat_yr = q5.set_index("year")
ax1.bar(seat_yr.index - 0.2, seat_yr["dem_seats"], width=0.4,
        color=BLUE, alpha=0.85, label="Dem seats")
ax1.bar(seat_yr.index + 0.2, seat_yr["rep_seats"], width=0.4,
        color=RED, alpha=0.85, label="Rep seats")
ax1.set_xlabel("Election Year")
ax1.set_ylabel("Seats Won")
ax1.set_xticks(seat_yr.index)
ax1.legend(loc="upper left")
ax1.set_title("Figure 1: House Seats Won by Party with National Generic Ballot")

ax2 = ax1.twinx()
ax2.plot(seat_yr.index, seat_yr["generic_ballot_margin"],
         color="black", marker="o", linewidth=2, label="Generic ballot (D−R)")
ax2.axhline(0, color=GRAY, linestyle="--", linewidth=0.8)
ax2.set_ylabel("Generic Ballot Margin (D−R, pct pts)")
ax2.legend(loc="upper right")

fig.tight_layout()
fig.savefig("/content/fig1_seats_by_year.png", dpi=150, bbox_inches="tight")
log.info("  Saved fig1_seats_by_year.png")
plt.close()

# ---------------------------------------------------------------------------
# Figure 2: Feature importance bar chart
# Rationale: explains which variables drive flip predictions — essential
#            for communicating model decisions to a non-technical audience.
# ---------------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(8, 6))
colors = [BLUE if i < 3 else GRAY for i in range(len(feat_imp))]
ax.barh(feat_imp["feature"][::-1], feat_imp["importance"][::-1],
        color=colors[::-1], edgecolor="white")
ax.set_xlabel("Feature Importance (Gradient Boosting)")
ax.set_title("Figure 2: Predictors of Party Seat Flip")
ax.xaxis.set_major_formatter(mtick.PercentFormatter(xmax=1))
fig.tight_layout()
fig.savefig("/content/fig2_feature_importance.png", dpi=150, bbox_inches="tight")
log.info("  Saved fig2_feature_importance.png")
plt.close()

# ---------------------------------------------------------------------------
# Figure 3: ROC curve with AUC annotation
# Rationale: publication-standard evaluation of binary classifier performance.
# ---------------------------------------------------------------------------
fpr, tpr, _ = roc_curve(y_test, y_prob)
fig, ax = plt.subplots(figsize=(6, 6))
ax.plot(fpr, tpr, color=BLUE, linewidth=2,
        label=f"Gradient Boosting (AUC = {test_auc:.2f})")
ax.plot([0, 1], [0, 1], color=GRAY, linestyle="--", linewidth=1)
ax.set_xlabel("False Positive Rate")
ax.set_ylabel("True Positive Rate")
ax.set_title("Figure 3: ROC Curve — Party Flip Prediction (2022 holdout)")
ax.legend()
fig.tight_layout()
fig.savefig("/content/fig3_roc_curve.png", dpi=150, bbox_inches="tight")
log.info("  Saved fig3_roc_curve.png")
plt.close()

# ---------------------------------------------------------------------------
# Figure 4: Demographic profile — competitive vs. safe districts
# Rationale: supports press release chart requirement; shows which district
#            characteristics correlate with electoral competitiveness.
# ---------------------------------------------------------------------------
comp_demo = con.execute("""
    SELECT
        CASE WHEN e.competitive THEN 'Competitive' ELSE 'Safe' END AS district_type,
        ROUND(AVG(dm.pct_college)   * 100, 1) AS college_pct,
        ROUND(AVG(dm.pct_nonwhite)  * 100, 1) AS nonwhite_pct,
        ROUND(AVG(dm.poverty_rate)  * 100, 1) AS poverty_pct,
        ROUND(AVG(dm.health_ins_rate) * 100, 1) AS insured_pct
    FROM elections e
    JOIN demographics dm ON e.district_id = dm.district_id AND e.year = dm.year
    GROUP BY district_type
""").fetchdf().set_index("district_type")

fig, axes = plt.subplots(1, 4, figsize=(13, 5))
metrics = ["college_pct", "nonwhite_pct", "poverty_pct", "insured_pct"]
labels  = ["% College Ed.", "% Non-white", "% in Poverty", "% Insured"]
palette = {c: BLUE if c == "Competitive" else RED for c in comp_demo.index}

for ax, metric, label in zip(axes, metrics, labels):
    bars = ax.bar(comp_demo.index, comp_demo[metric],
                  color=[palette[c] for c in comp_demo.index],
                  edgecolor="white", width=0.5)
    ax.set_title(label, fontsize=11)
    ax.set_ylabel("%" if ax == axes[0] else "")
    ax.yaxis.set_major_formatter(mtick.PercentFormatter(xmax=100))
    for bar in bars:
        ax.text(bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 0.3,
                f"{bar.get_height():.1f}%",
                ha="center", va="bottom", fontsize=9)

fig.suptitle("Figure 4: Demographic Profile of Competitive vs. Safe Districts",
             fontsize=13, fontweight="bold")
fig.tight_layout()
fig.savefig("/content/fig4_demographics.png", dpi=150, bbox_inches="tight")
log.info("  Saved fig4_demographics.png")
plt.close()

# ---------------------------------------------------------------------------
# Figure 5: Flip probability distribution by true outcome
# Rationale: shows model calibration — do high-probability flips actually flip?
# ---------------------------------------------------------------------------
pred_df = results_df.merge(
    model_df[["district_id", "year", TARGET]],
    on=["district_id", "year"]
)
fig, ax = plt.subplots(figsize=(8, 5))
for val, label, color in [(0, "Did Not Flip", BLUE), (1, "Flipped", RED)]:
    subset = pred_df[pred_df[TARGET] == val]["flip_probability"]
    ax.hist(subset, bins=20, alpha=0.65, color=color, label=label,
            density=True, edgecolor="white")
ax.set_xlabel("Predicted Flip Probability")
ax.set_ylabel("Density")
ax.set_title("Figure 5: Model-Predicted Flip Probability by Actual Outcome")
ax.legend()
fig.tight_layout()
fig.savefig("/content/fig5_flip_probability.png", dpi=150, bbox_inches="tight")
log.info("  Saved fig5_flip_probability.png")
plt.close()

# ===========================================================================
# SUMMARY
# ===========================================================================
log.info("=" * 60)
log.info("PIPELINE COMPLETE")
log.info("=" * 60)

summary = con.execute("""
    SELECT table_name, estimated_size
    FROM duckdb_tables()
""").fetchdf()
log.info(f"\nFinal table summary:\n{summary.to_string()}")

print("\n" + "=" * 60)
print("Pipeline complete. Files saved to /content/:")
print("  house_elections.duckdb       — DuckDB database (5 tables)")
print("  fig1_seats_by_year.png")
print("  fig2_feature_importance.png")
print("  fig3_roc_curve.png")
print("  fig4_demographics.png")
print("  fig5_flip_probability.png")
print("  06_pipeline.log")
print(f"\nModel performance (2022 holdout):")
print(f"  ROC-AUC:  {test_auc:.3f}")
print(f"  CV AUC:   {cv_scores.mean():.3f} ± {cv_scores.std():.3f}")
print("=" * 60)

OUTPUT_DIR = "/content/tables"
os.makedirs(OUTPUT_DIR, exist_ok=True)

tables = ["districts", "elections", "demographics",
          "national_context", "results_model"]

for table in tables:
    out_path = f"{OUTPUT_DIR}/{table}.parquet"
    con.execute(f"COPY {table} TO '{out_path}' (FORMAT PARQUET)")
    size_kb = os.path.getsize(out_path) / 1024
    print(f"  {table}.parquet — {size_kb:.1f} KB")

print("\nDone. Download from /content/tables/ in the sidebar.")

con.close()
