# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/141tcb2OUrZYPUIe-Hp9sqyj7vlWPlhLJ
"""

!pip install pandas requests pyarrow -q

"""
06_enrich_dataset.py  (Google Colab version)
=============================================
Enriches combined_dataset.csv with additional predictive features
and saves the result as both CSV and Parquet.

COLAB USAGE
-----------
1. Upload combined_dataset.csv using the sidebar (Files panel)
2. Run this cell:

   !pip install pandas requests pyarrow -q

3. Paste or run this script. Output files will appear in the
   sidebar at /content/ and can be downloaded from there.

NEW COLUMNS ADDED
-----------------
From Census Bureau API (CVAP):
  cvap_total        — citizen voting age population
  cvap_turnout_rate — total_votes / cvap_total

Derived from existing MIT election data:
  incumbent_running — True if same party held seat prior cycle
  open_seat         — True if seat changed party from prior cycle

Manually compiled lookup tables (edit at top of file if needed):
  generic_ballot_margin — national D minus R generic ballot margin
  redistricting_year    — True if cycle used freshly redrawn maps
"""

import os
import logging
import requests
import pandas as pd

# ---------------------------------------------------------------------------
# Logging — writes to Colab's /content/ folder
# ---------------------------------------------------------------------------
logging.basicConfig(
    filename="/content/06_enrich_dataset.log",
    level=logging.INFO,
    format="%(asctime)s  %(levelname)s  %(message)s",
)
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths — all pointing to /content/ (Colab sidebar)
# ---------------------------------------------------------------------------
INPUT_PATH  = "/content/combined_dataset.csv"
OUT_CSV     = "/content/combined_dataset_enriched.csv"
OUT_PARQUET = "/content/combined_dataset_enriched.parquet"

# ---------------------------------------------------------------------------
# Lookup tables — edit these if you have better numbers
# ---------------------------------------------------------------------------

# National generic congressional ballot: Democrat minus Republican margin
# Positive = Democrats favored nationally. Negative = Republicans favored.
# Sources: RealClearPolitics final averages.
GENERIC_BALLOT = {
    2012: -1.0,   # R+1
    2014: -5.7,   # R+5.7 (Republican wave)
    2016: -1.0,   # R+1
    2018:  8.6,   # D+8.6 (Democratic wave)
    2020:  6.8,   # D+6.8
    2022: -2.8,   # R+2.8
    2024: -1.5,   # R+1.5 (approximate)
}

# Cycles that used maps redrawn after a decennial Census
REDISTRICTING_CYCLES = {2012, 2022}

# FIPS code → postal abbreviation (for Census API calls)
FIPS_TO_POSTAL = {
    "01": "AL", "02": "AK", "04": "AZ", "05": "AR", "06": "CA",
    "08": "CO", "09": "CT", "10": "DE", "11": "DC", "12": "FL",
    "13": "GA", "15": "HI", "16": "ID", "17": "IL", "18": "IN",
    "19": "IA", "20": "KS", "21": "KY", "22": "LA", "23": "ME",
    "24": "MD", "25": "MA", "26": "MI", "27": "MN", "28": "MS",
    "29": "MO", "30": "MT", "31": "NE", "32": "NV", "33": "NH",
    "34": "NJ", "35": "NM", "36": "NY", "37": "NC", "38": "ND",
    "39": "OH", "40": "OK", "41": "OR", "42": "PA", "44": "RI",
    "45": "SC", "46": "SD", "47": "TN", "48": "TX", "49": "UT",
    "50": "VT", "51": "VA", "53": "WA", "54": "WV", "55": "WI",
    "56": "WY",
}

# Election year → closest preceding ACS 5-year release
ACS_YEAR_MAP = {
    2012: 2012,
    2014: 2014,
    2016: 2016,
    2018: 2018,
    2020: 2020,
    2022: 2022,
    2024: 2022,   # 2024 ACS not yet published
}


# ===========================================================================
# 1. LOAD
# ===========================================================================
def load_combined(path: str) -> pd.DataFrame:
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"\n\nFile not found: {path}\n"
            "Make sure combined_dataset.csv is uploaded to Colab first.\n"
            "In the left sidebar: Files → Upload → select combined_dataset.csv"
        )
    df = pd.read_csv(path)
    log.info(f"Loaded {path}: {len(df):,} rows, {df.shape[1]} columns")
    return df


# ===========================================================================
# 2. CVAP — Citizen Voting Age Population
# ===========================================================================
def fetch_cvap_one_year(acs_year: int) -> pd.DataFrame:
    """
    Pull CVAP from Census Bureau ACS 5-year estimates for one year.

    Variables:
      B05003_008E — Male citizens 18+
      B05003_019E — Female citizens 18+
    """
    base = f"https://api.census.gov/data/{acs_year}/acs/acs5"
    vars_ = "B05003_008E,B05003_019E"
    rows = []

    for fips, postal in FIPS_TO_POSTAL.items():
        url = (
            f"{base}?get=NAME,{vars_}"
            f"&for=congressional+district:*"
            f"&in=state:{fips}"
        )
        try:
            resp = requests.get(url, timeout=20)
            resp.raise_for_status()
            data = resp.json()
            for rec in data[1:]:
                name, male_cit, female_cit, state_fips, cd_num = rec
                try:
                    cvap = int(male_cit) + int(female_cit)
                except (TypeError, ValueError):
                    cvap = None
                district_id = f"{postal}-{cd_num.zfill(2)}"
                rows.append({
                    "district_id": district_id,
                    "acs_year":    acs_year,
                    "cvap_total":  cvap,
                })
        except Exception as exc:
            log.warning(f"CVAP fetch failed — {postal} {acs_year}: {exc}")

    df = pd.DataFrame(rows)
    log.info(f"CVAP fetched for {acs_year}: {len(df):,} rows")
    return df


def build_cvap_table() -> pd.DataFrame:
    unique_acs_years = sorted(set(ACS_YEAR_MAP.values()))
    pieces = []
    for yr in unique_acs_years:
        print(f"    Fetching CVAP {yr}…")
        pieces.append(fetch_cvap_one_year(yr))
    return pd.concat(pieces, ignore_index=True)


def merge_cvap(df: pd.DataFrame) -> pd.DataFrame:
    cvap = build_cvap_table()

    df["acs_year"] = df["year"].map(ACS_YEAR_MAP)
    df = df.merge(
        cvap[["district_id", "acs_year", "cvap_total"]],
        on=["district_id", "acs_year"],
        how="left",
    )

    # Turnout rate only if total votes column exists
    if "totalvotes" in df.columns:
        df["cvap_turnout_rate"] = (df["totalvotes"] / df["cvap_total"]).clip(upper=1.0)
        log.info("Added cvap_turnout_rate")
    else:
        log.info("No totalvotes column — skipping cvap_turnout_rate")

    df = df.drop(columns=["acs_year"])
    log.info("CVAP merge complete")
    return df


# ===========================================================================
# 3. INCUMBENCY
# ===========================================================================
def add_incumbency(df: pd.DataFrame) -> pd.DataFrame:
    """
    Derive incumbency proxies from the election data itself.

    incumbent_running — same party won this district the prior cycle
    open_seat         — seat changed party from prior cycle
    """
    df = df.sort_values(["district_id", "year"]).reset_index(drop=True)

    prior = (
        df[["district_id", "year", "winner"]]
        .copy()
        .rename(columns={"winner": "prior_winner"})
    )
    prior["year"] = prior["year"] + 2

    df = df.merge(
        prior[["district_id", "year", "prior_winner"]],
        on=["district_id", "year"],
        how="left",
    )

    df["incumbent_running"] = df["winner"] == df["prior_winner"]
    df["open_seat"]         = df["prior_winner"].notna() & (df["winner"] != df["prior_winner"])
    df.loc[df["prior_winner"].isna(), ["incumbent_running", "open_seat"]] = None

    df = df.drop(columns=["prior_winner"])
    log.info("Incumbency columns added")
    return df


# ===========================================================================
# 4. NATIONAL CONTEXT
# ===========================================================================
def add_national_context(df: pd.DataFrame) -> pd.DataFrame:
    df["generic_ballot_margin"] = df["year"].map(GENERIC_BALLOT)
    df["redistricting_year"]    = df["year"].isin(REDISTRICTING_CYCLES)

    missing = df["generic_ballot_margin"].isna().sum()
    if missing > 0:
        log.warning(f"{missing} rows missing generic ballot — add year to GENERIC_BALLOT dict")

    log.info("National context columns added")
    return df


# ===========================================================================
# 5. COOK PVI  (optional)
# ===========================================================================
def add_cook_pvi(df: pd.DataFrame, pvi_path: str = "/content/cook_pvi.csv") -> pd.DataFrame:
    """
    Merge Cook PVI if you have the file uploaded to Colab.

    To use:
      1. Create cook_pvi.csv with columns: district_id, year, cook_pvi_score
         (negative = Republican lean, positive = Democratic lean)
      2. Upload it to Colab sidebar
      3. Re-run — it will merge automatically

    If the file isn't there, this step is silently skipped.
    """
    if not os.path.exists(pvi_path):
        print("  Cook PVI skipped — upload cook_pvi.csv to /content/ to include it")
        log.info("Cook PVI: file not found, skipping")
        return df

    pvi = pd.read_csv(pvi_path)
    required = {"district_id", "year", "cook_pvi_score"}
    if not required.issubset(pvi.columns):
        print(f"  Cook PVI skipped — CSV needs columns: {required}")
        log.warning(f"Cook PVI CSV missing required columns: {required}")
        return df

    df = df.merge(pvi[list(required)], on=["district_id", "year"], how="left")
    filled = df["cook_pvi_score"].notna().sum()
    print(f"  Cook PVI merged: {filled:,} values")
    log.info(f"Cook PVI merged: {filled:,} values")
    return df


# ===========================================================================
# 6. SAVE
# ===========================================================================
def save_outputs(df: pd.DataFrame) -> None:
    # CSV
    df.to_csv(OUT_CSV, index=False)
    csv_mb = os.path.getsize(OUT_CSV) / 1e6
    print(f"\n  CSV saved:     {OUT_CSV}  ({csv_mb:.2f} MB)")
    log.info(f"CSV saved: {OUT_CSV} ({csv_mb:.2f} MB, {len(df):,} rows)")

    print(f"\n  Final shape: {df.shape[0]:,} rows × {df.shape[1]} columns")
    print(f"  New columns: cvap_total, incumbent_running, open_seat,")
    print(f"               generic_ballot_margin, redistricting_year")
    print(f"\n  Download from the Colab sidebar (Files panel on the left)")


# ===========================================================================
# 7. MAIN
# ===========================================================================
def main():
    print("=" * 60)
    print("Enriching combined_dataset.csv")
    print("=" * 60)

    print("\n[1/5] Loading combined_dataset.csv…")
    df = load_combined(INPUT_PATH)
    print(f"  {len(df):,} rows, {df.shape[1]} columns")
    print(f"  Columns found: {list(df.columns)}")

    print("\n[2/5] Fetching CVAP from Census Bureau API…")
    print("  (makes ~50 API calls per year — takes ~2 minutes total)")
    try:
        df = merge_cvap(df)
        print(f"  cvap_total non-null: {df['cvap_total'].notna().sum():,} rows")
    except Exception as exc:
        log.error(f"CVAP merge failed: {exc}")
        print(f"  WARNING: CVAP fetch failed ({exc}). Continuing without it.")

    print("\n[3/5] Deriving incumbency columns…")
    df = add_incumbency(df)
    inc = df['incumbent_running'].sum() if df['incumbent_running'].notna().any() else 0
    opn = df['open_seat'].sum() if df['open_seat'].notna().any() else 0
    print(f"  incumbent_running: {inc:.0f} rows True")
    print(f"  open_seat:         {opn:.0f} rows True")

    print("\n[4/5] Adding generic ballot and redistricting flag…")
    df = add_national_context(df)
    print(f"  generic_ballot_margin added for years: {sorted(GENERIC_BALLOT.keys())}")

    print("\n[4.5] Checking for optional Cook PVI file…")
    df = add_cook_pvi(df)

    print("\n[5/5] Saving outputs…")
    save_outputs(df)

    print("\nDone. Log at /content/06_enrich_dataset.log")
    print("=" * 60)


if __name__ == "__main__":
    main()